#!/bin/sh

#Run as www-data

mktexpk --mfmode / --bdpi 600 --mag 1+0/600 --dpi 600 ecsl1000c
mktexpk --mfmode / --bdpi 600 --mag 1+0/600 --dpi 600 ecsl1000
mktexpk --mfmode / --bdpi 600 --mag 1+0/600 --dpi 600 ecbx1000
mktexpk --mfmode / --bdpi 600 --mag 1+0/600 --dpi 600 ecrm1000
mktexpk --mfmode / --bdpi 600 --mag 1+0/600 --dpi 600 ecbx1200
mktexpk --mfmode / --bdpi 600 --mag 1+0/600 --dpi 600 ecbx1440
mktexpk --mfmode / --bdpi 600 --mag 1+0/600 --dpi 600 ecrm1200
mktexpk --mfmode / --bdpi 600 --mag 1+0/600 --dpi 600 ecrm1728
mktexpk --mfmode / --bdpi 600 --mag 1+0/600 --dpi 600 ecss1000

