#based on http://blog.bleything.net/2006/06/27/dry-out-your-database-yml

login: &login
  adapter: mysql
  host: localhost
<% if `uname -n`.strip == "ampere.aketzu.net" %>
  username: tikki
  password: D.uMJK4pjxnrE9uH
<% else %>
  username: root
  password: 
<% end %>
<% if File.exist? "/var/run/mysqld/mysqld.sock" %>
  socket: /var/run/mysqld/mysqld.sock
<% elsif File.exist? "/tmp/mysql.sock" %>
  socket: /tmp/mysql.sock
<% end %>

development:
  database: tikki_development
  <<: *login

test:
  database: tikki_test
  <<: *login

production:
  database: tikki_production
  <<: *login
